apiVersion: v1
kind: ConfigMap
metadata:
  name: jira-config
  labels:
    app: jira
data:
  JVM_MINIMUM_MEMORY: 2048m
  JVM_MAXIMUM_MEMORY: 4096m

  #ATL_PROXY_NAME: jira.vmware1.discovery.spectrocloud.com
  #ATL_PROXY_PORT: '443'

  ATL_JDBC_URL: jdbc:mysql://my-cluster-mysql:3306/jiradb
  # TODO username/password use secret instead
  ATL_JDBC_USER: jira
  ATL_JDBC_PASSWORD: secure1
  ATL_DB_DRIVER: com.mysql.jdbc.Driver
  ATL_DB_TYPE: mysql57
