apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  ROOT_PASSWORD: super-secure1
  USER: jira
  PASSWORD: secure1
  DATABASE: jiradb
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  replicas: 1
  mysqlVersion: "5.7"
  secretName: my-cluster-secret
  volumeSpec:
    persistentVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
