---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    k8s.t-mobile.com/akmid: APM0103270
    k8s.t-mobile.com/director: KSchmid22
    kubernetes.io/metadata.name: images
  name: images
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-pull-view
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-pull-view-rb
  namespace: images
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-pull-view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes
