apiVersion: v1
kind: Secret
metadata:
  name: ldap-secret
  namespace: dex
data:
  role_id: ${base64encode(vault_role_id)}
  secret_id: ${base64encode(vault_secret_id)}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultconfig
  namespace: dex
data:
  config-init.hcl: |
    exit_after_auth = true
    pid_file = "/home/vault/pidfile"
    auto_auth {
      method "approle" {
        mount_path = "auth/approle"
        config = {
          role_id_file_path = "/vault/custom/role_id"
          secret_id_file_path = "/vault/custom/secret_id"
          remove_secret_id_file_after_reading = false
        }
      }
      sink "file" {
        config = {
          path = "/home/vault/.vault-token"
        }
      }
    }
    template {
      destination = "/vault/secrets/config"
      contents = <<-EOD
        {{ with secret "pe/applications/dex/dex-px-snd2001" }}
          export BINDDN="{{ .Data.LDAP_BIND_DN }}"
          export BINDPW="{{ .Data.LDAP_BIND_PWD }}"
        {{ end }}
      EOD
    }
    vault {
      address = "${vault_address}"
      tls_skip_verify = "true"
    }
