manifests:
  byo-manifest:
    contents: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: ldap-secret
        namespace: dex
      stringData:
        role_id: 74cb0cd6-89a2-2693-7f38-d2b196f8d49c
        secret_id: 0a45165d-5e0b-21c0-e971-5d2d37505c60
      ---
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: vaultconfig
        namespace: dex
      data:
        config-init.hcl: |
          exit_after_auth = true

          pid_file = "/home/vault/pidfile"

          auto_auth {
            method "approle" {
              mount_path = "auth/approle"
              config = {
                role_id_file_path = "/vault/custom/role_id"
                secret_id_file_path = "/vault/custom/secret_id"
                remove_secret_id_file_after_reading = false
              }
            }

            sink "file" {
              config = {
                path = "/home/vault/.vault-token"
              }
            }
          }

          template {
            destination = "/vault/secrets/config"
            contents = <<-EOD
              {{ with secret "secret/ldap/creds" }}
                export BINDDN="{{ .Data.data.bind_dn }}"
                export BINDPW="{{ .Data.data.bind_pw }}"
              {{ end }}
            EOD
          }

          vault {
            address = "${vault_addr}"
          }
      ---
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/tls
      metadata:
        name: default-tls
        namespace: nginx
      stringData:
        ${indent(8, certkey)}
