apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: default-tls
  namespace: nginx
data:
  tls.key: |
    ${indent(4, tls_key_contents)}
  tls.crt: |
    ${indent(4, tls_crt_contents)}
  ca.crt: |
    ${indent(4, ca_crt_contents)}