# This is a basic workflow that is manually triggered

name: Terraform Plan

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

env:
  SPECTROCLOUD_TF_PATH: terraform-test

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  plan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.SPECTROCLOUD_TF_PATH }}
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -backend-config="endpoints=[\"35.203.171.218:2379\"]"

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -no-color -input=false \
        -var 'sc_host=${{ secrets.SC_HOST }}' \
        -var 'sc_project_name=${{ secrets.SC_PROJECT_NAME }}' \
        -var 'sc_username=${{ secrets.SC_USERNAME }}' \
        -var 'sc_password=${{ secrets.SC_PASSWORD }}'
      continue-on-error: true
    - uses: actions/github-script@v3
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌 \`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️ \`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖 ${{ steps.validate.outputs.stdout }}
          #### Terraform Plan 📖 \`${{ steps.plan.outcome }}\`

          <details open><summary>Show Plan</summary>

          \`\`\`
          ${process.env.PLAN}
          \`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.SPECTROCLOUD_TF_PATH }}\`, Workflow: \`${{ github.workflow }}\`*`;

          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
